#!/bin/bash

dir=$(pwd) #change this to the absolute path of directory when using with dmenu

$dir/position.sh $(bash $dir/primaryselect.sh | dmenu -l 20 -p 'primary monitor:' | awk '{print $1}') $($dir/monitorconf.sh | dmenu -l 20 -p 'hdmi monitor layout:')
